import json
import string
import random
from json import JSONDecodeError
from datetime import datetime

from commadline import Quantity

def Register(type,gamers_json_file,sellers_json_file,Email_ID,Username,Password,Contact_Number):
    '''Register Function || Already Given'''
    if type.lower()=='seller':
        f=open(sellers_json_file,'r+')
        d={
            "Email":Email_ID,
            "Username":Username,
            "Password":Password,
            "Contact Number":Contact_Number,
        }
        try:
            content=json.load(f)
            if d not in content and d["Username"] not in str(content):
                content.append(d)
                f.seek(0)
                f.truncate()
                json.dump(content,f)
        except JSONDecodeError:
            l=[]
            l.append(d)
            json.dump(l,f)
        f.close()
        return True
    elif type.lower()=='gamer':
        f=open(gamers_json_file,'r+')
        d={
            "Email":Email_ID,
            "Username":Username,
            "Password":Password,
            "Contact Number":Contact_Number,
            "Wishlist":[],
            "Cart":[],
        }
        try:
            content=json.load(f)
            if d not in content and d["Username"] not in str(content):
                content.append(d)
                f.seek(0)
                f.truncate()
                json.dump(content,f)
        except JSONDecodeError:
            l=[]
            l.append(d)
            json.dump(l,f)
        f.close()

def Login(type,gamers_json_file,sellers_json_file,Username,Password):
    '''Login Functionality || Return True if successfully logged in else False || Already Given'''
    d=0
    if type.lower()=='seller':
        f=open(sellers_json_file,'r+')
    else:
        f=open(gamers_json_file,'r+')
    try:
        content=json.load(f)
    except JSONDecodeError:
        return False
    for i in range(len(content)):
        if content[i]["Username"]==Username and content[i]["Password"]==Password:
            d=1
            break
    f.seek(0)
    f.truncate()
    json.dump(content,f)
    f.close()
    if d==0:
        return False
    return True

def AutoGenerate_ProductID():
    '''Return a autogenerated random product ID || Already Given'''
    product_ID=''.join(random.choices(string.ascii_uppercase+string.digits,k=4))
    return product_ID

def AutoGenerate_OrderID():
    '''Return a autogenerated random product ID || Already Given'''
    Order_ID=''.join(random.choices(string.ascii_uppercase+string.digits,k=3))
    return Order_ID

def days_between(d1, d2):
    '''Calculating the number of days between two dates || Already Given'''
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)

def Create_Product(owner,product_json_file,product_ID,product_title,product_type,price_per_day,total_stock_available):
    '''Creating a product || Return True if successfully created else False'''
    '''Write your code below'''
    data={
         "Seller Username": owner, 
         "Product ID": product_ID, 
         "Product Title": product_title, 
         "Product Type": product_type, 
         "Price Per Day": price_per_day, 
         "Total Stock Available": total_stock_available
         }
    fp=open(product_json_file,"r+")
    try:
        content=json.load(fp)
        if data not in content:
            content.append(data)
            fp.seek(0)
            fp.truncate()
            json.dump(content,fp)
    except JSONDecodeError:
        l=[]
        l.append(data)
        json.dump(l,fp)
    fp.close()
    return True
    

def Fetch_all_Products_created_by_seller(owner,product_json_file):
    '''Get all products created by the seller(owner)'''
    '''Write your code below'''
    all_seller_product_list=[]
    fp=open(product_json_file,"r")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Seller Username"]==owner:
            all_seller_product_list.append(content[i])
    fp.close()
    return all_seller_product_list

def Fetch_all_products(products_json_file):
    '''Get all products created till now || Helper Function || Already Given'''
    All_Products_list=[]
    fp=open(products_json_file,'r')
    try:
        content=json.load(fp)
        All_Products_list=content
    except JSONDecodeError:
        pass
    fp.close()
    return All_Products_list

def Fetch_Product_By_ID(product_json_file,product_ID):
    '''Get product deatils by product ID'''
    '''Write your code below'''
    All_Products_list=[]
    fp=open(product_json_file,"r")
    try:
        content=json.load(fp)
        for i in range(len(content)):
            if content[i]["Product ID"]==product_ID:
               All_Products_list=content[i]
    except JSONDecodeError:
        fp.close()
        return False
    fp.close()
    return All_Products_list


def Update_Product(Username,product_json_file,product_ID,detail_to_be_updated,new_value):
    '''Updating Product || Return True if successfully updated else False'''
    '''Write your code below'''
    fp=open(product_json_file,"r+")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Product ID"]==product_ID:
            try:
                a=content[i][detail_to_be_updated]
            except KeyError:
                return False
            content[i][detail_to_be_updated]=new_value
            fp.seek(0)
            fp.truncate()
            json.dump(content,fp)
            fp.close()
            return True
        fp.close()
        return False

def Add_item_to_wishlist(Username,product_ID,gamers_json_file):
    '''Add Items to wishlist || Return True if added successfully else False'''
    '''Write your code below'''
    wishlist=[]
    fp=open(gamers_json_file,"r+")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Product ID"]==product_ID:
            content[i]["Wishlist"]=content[i]
            fp.seek(0)
            fp.truncate()
            json.dump(content,fp)
            fp.close()
            return True
    else:
        fp.close()
        return False



def Remove_item_from_wishlist(Username,product_ID,gamers_json_file):
    '''Remove items from wishlist || Return True if removed successfully else False'''
    '''Write your code below'''
    fp=open(gamers_json_file,"r+")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Product ID"]==product_ID:
            content[i]["Wishlist"]=[]
            fp.seek(0)
            fp.truncate()
            json.dump(content,fp)
            fp.close()
            return True
    else:
        fp.close()
        return False

    

def Add_item_to_cart(Username,product_ID,Quantity,gamers_json_file,booking_start_date,booking_end_date,products_json_file):
    '''Add item to the cart || Check whether the quantity mentioned is available || Return True if added successfully else False'''
    '''Add the Product ID, Quantity, Price, Booking Start Date, Booking End Date in the cart as list of dictionaries'''
    '''Write your code below'''
    fp1=open(gamers_json_file,"r+")
    fp2=open(products_json_file,"r+")
    c1=json.load(fp1)
    c2=json.load(fp2)
    for i in range(len(c2)):
        if c2[i][ "Product ID"]==product_ID:
            if c2[i]["Total Stock Available"]>=Quantity:
                for j in range(len(c1)):
                    if c1[j]["Ordered by"]==Username:
                        c1[j]["Items"][j]["Booking Start Date"]=booking_start_date
                        c1[j]["Items"][j][ "Booking End Date"]=booking_end_date
                        json.dump(c1,fp1)
                        fp1.close()
                        fp2.close()
                        return True
    else:
        fp1.close()
        fp2.close()
        return False




    

    

def Remove_item_from_cart(Username,product_ID,gamers_json_file):
    '''Remove items from the cart || Return True if removed successfully else False'''
    '''Write your code below'''
    fp=open(gamers_json_file,"r+")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Product ID"]==product_ID:
            content[i]["Cart"]=[]
            fp.seek(0)
            fp.truncate()
            json.dump(content,fp)
            fp.close()
            return True
    else:
        fp.close()
        return False
    

def View_Cart(Username,gamers_json_file):
    '''Return the current cart of the user'''
    '''Write your code below'''
    current_cart=[]
    fp=open(gamers_json_file,"r")
    content=json.load(fp)
    for i in range(content):
        if content[i]["Username"]==Username:
            current_cart.append(content[i]["Cart"])
    fp.close()
    return current_cart

def Place_order(Username,gamers_json_file,Order_Id,orders_json_file,products_json_file):
    '''Place order || Return True is order placed successfully else False || Decrease the quantity of the product orderd if successfull'''
    '''Write your code below'''
    fp1=open(gamers_json_file,"r+")
    fp2=open(products_json_file,"r+")
    fp3=open(orders_json_file,"r+")
    c1=json.load(fp1)
    c2=json.load(fp2)
    c3=json.load(fp3)
    for i in range(len(c1)):
        if c1[i]["Username"]==Username:
            q=0
            for j in range(len(c2[i]["Cart"])):
                q+=c2[i]["Cart"][j]["Quantity"]

            for j in range(len(c2)):
                if c2[j]["Product ID"]==c1[i]["Cart"][j]["Product ID"]:
                    if c2[j][ "Total Stock Available"]-q>=0:
                        fp1.close()
                        fp2.close()
                        fp3.close()
                        return True
        
        else:
            fp1.close()
            fp2.close()
            fp3.close()
            False








    

def View_User_Details(gamers_json_file,Username):
    '''Return a list with all gamer details based on the username || return an empty list if username not found'''
    '''Write your code below'''
    g_details=[]
    fp=open(gamers_json_file,"r")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Username"]==Username:
            g_details.append(content[i])
    fp.close()
    return g_details

    

def Update_User(gamers_json_file,Username,detail_to_be_updated,updated_detail):
    '''Update the detail_to_be_updated of the user to updated_detail || Return True if successful else False'''
    '''Write your code below'''
    fp=open(gamers_json_file,"r+")
    content=json.load(fp)
    for i in range(len(content)):
        if content[i]["Username"]==Username:
            try:
                a=content[i][detail_to_be_updated]
            except KeyError:
                return False
            content[i][detail_to_be_updated]=updated_detail
            fp.seek(0)
            fp.truncate()
            json.dump(content,fp)
            fp.close()
            return True
        fp.close()
        return False
    

def Fetch_all_orders(orders_json_file,Username):
    '''Fetch all previous orders for the user and return them as a list'''
    '''Write your code below'''
    all_orders=[]
    fp=open(orders_json_file,"r")
    
    try:
        content=json.load(fp)
        all_orders=content
    except JSONDecodeError:
        fp.close()
        return False
    fp.close()
    return all_orders
    
    

